import "cypress-axe";
/// <reference types="cypress" />

context("Navigation", () => {
  beforeEach(() => {
    cy.visit("https://vjkumar57.github.io/SiteNavigation/#");
    cy.injectAxe();
    cy.checkA11y(undefined, { retries: 20, interval: 10 });
    cy.get("a").contains("Quiz").type("{enter}");
    cy.get("a").contains("About").type("{enter}");
    cy.get("a").contains("Dashboard").type("{enter}");
    cy.get("a").contains("Home").type("{enter}");
  });

  describe("Navigation", () => {
    beforeEach(() => {
      cy.visit("https://vjkumar57.github.io/SiteNavigation/#");
    });

    it("should have correct page title", () => {
      cy.title().should("eq", "Let's Learn Accessibility");
    });

    it("should have correct lang attribute", () => {
      cy.get("html").should("have.attr", "lang", "en");
    });

    it("should have alt text for the profile image", () => {
      cy.get("img.profile-picture")
        .should("have.attr", "alt")
        .should("not.be.empty");
      cy.get("img.profile-picture").should(
        "have.attr",
        "alt",
        "Profile Picture"
      );
    });
  });

  it("should validate tabbing order from Home to Dashboard menu", () => {
    cy.get("a").contains("Home").focus().realPress("Tab");
    cy.get("a").contains("Dashboard").should("be.focused");
  });
  it("should validate tabbing order from Dashboard to Trainings menu", () => {
    cy.get("a").contains("Dashboard").focus().realPress("Tab");
    cy.get("a").contains("Trainings").should("be.focused");
  });
  it("should validate tabbing order from Trainings to Quiz menu", () => {
    cy.get("a").contains("Trainings").focus().realPress("Tab");
    cy.get("a").contains("Quiz").should("be.focused");
  });
});

/*

  //The below code were automatically generated by Cypress - Please ignore

  it('cy.go() - go back or forward in the browser\'s history', () => {
    // https://on.cypress.io/go

    cy.location('pathname').should('include', 'navigation')

    cy.go('back')
    cy.location('pathname').should('not.include', 'navigation')

    cy.go('forward')
    cy.location('pathname').should('include', 'navigation')

    // clicking back
    cy.go(-1)
    cy.location('pathname').should('not.include', 'navigation')

    // clicking forward
    cy.go(1)
    cy.location('pathname').should('include', 'navigation')
  })

  it('cy.reload() - reload the page', () => {
    // https://on.cypress.io/reload
    cy.reload()

    // reload the page without using the cache
    cy.reload(true)
  })

  it('cy.visit() - visit a remote url', () => {
    // https://on.cypress.io/visit

    // Visit any sub-domain of your current domain

    // Pass options to the visit
    cy.visit('https://example.cypress.io/commands/navigation', {
      timeout: 50000, // increase total time for the visit to resolve
      onBeforeLoad (contentWindow) {
        // contentWindow is the remote page's window object
        expect(typeof contentWindow === 'object').to.be.true
      },
      onLoad (contentWindow) {
        // contentWindow is the remote page's window object
        expect(typeof contentWindow === 'object').to.be.true
      },
    })
    }) */

/* code for keyboard trap and focus visibile but not working need to check
     it('should not have keyboard trap', () => {
      cy.checkA11y(undefined, {
        rules: {
          'keyboard-trap': { enabled: true },
        },
      });
    });
  
    it('should have focus styles for interactive elements', () => {
      cy.checkA11y(undefined, {
        rules: {
          'focus-visible': { enabled: true },
        },
      });
    }); */
